// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1omJtS_o679KRrqCMCZLqHNG_Qxbq0fA',
    appId: '1:889477084684:web:ed4da877d9127b73c7e029',
    messagingSenderId: '889477084684',
    projectId: 'angry-mark',
    authDomain: 'angry-mark.firebaseapp.com',
    storageBucket: 'angry-mark.appspot.com',
    measurementId: 'G-S4BXXKCBZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1WIjOOnPysSuETPw65nylZw9wfCkJwE',
    appId: '1:889477084684:android:1af05f4c357804e6c7e029',
    messagingSenderId: '889477084684',
    projectId: 'angry-mark',
    storageBucket: 'angry-mark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QxJT7zNs16f3gLb-HXVO6qWT-Ixp5NI',
    appId: '1:889477084684:ios:6d608d5c61c0f8aec7e029',
    messagingSenderId: '889477084684',
    projectId: 'angry-mark',
    storageBucket: 'angry-mark.appspot.com',
    iosBundleId: 'com.angryman.hng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QxJT7zNs16f3gLb-HXVO6qWT-Ixp5NI',
    appId: '1:889477084684:ios:2b2cc92cd1311c0fc7e029',
    messagingSenderId: '889477084684',
    projectId: 'angry-mark',
    storageBucket: 'angry-mark.appspot.com',
    iosBundleId: 'com.example.angryMark.RunnerTests',
  );
}
